# Generated by Django 5.0.6 on 2024-07-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='Tournament', max_length=50),
        ),
    ]
