# Generated by Django 5.0.6 on 2024-07-07 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_tournament_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournament',
            new_name='TournamentDB',
        ),
    ]
