# Generated by Django 5.0.6 on 2024-07-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_alter_gamedb_players_username_alter_gamedb_winners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedb',
            name='players_username',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='gamedb',
            name='winners',
            field=models.JSONField(default=[]),
        ),
    ]
