# Generated by Django 5.0.6 on 2024-07-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('profile_pic', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('is_playing', models.BooleanField(default=False)),
                ('grade', models.IntegerField(default=0)),
            ],
        ),
    ]
