# Generated by Django 5.0.6 on 2024-09-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='status',
            field=models.CharField(default="Hello, I'm new here!", max_length=20),
        ),
    ]
