# Generated by Django 5.0.6 on 2024-07-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0002_alter_userinfos_options_alter_userinfos_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfos',
            name='total_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfos',
            name='total_victories',
            field=models.IntegerField(default=0),
        ),
    ]
