# Generated by Django 5.0.6 on 2024-09-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0002_alter_userinfos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='status',
            field=models.CharField(default="Hello, I'm new here!", max_length=142),
        ),
    ]
