# Generated by Django 5.0.6 on 2024-09-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_game_date'),
        ('userManager', '0002_matchresults_userinfos_match_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='match_history',
            field=models.ManyToManyField(blank=True, to='database.game'),
        ),
    ]
