# Generated by Django 5.0.6 on 2024-07-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0004_userinfos_skin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfos',
            name='last_tournament_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
