# Generated by Django 5.0.6 on 2024-07-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0005_userinfos_last_tournament_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='skin',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
