# Generated by Django 5.0.6 on 2024-07-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0006_alter_userinfos_skin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfos',
            name='is_3d',
            field=models.BooleanField(default=False),
        ),
    ]
