# Generated by Django 5.0.6 on 2024-09-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0007_userinfos_is_3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
