# Generated by Django 5.0.6 on 2024-09-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0008_alter_userinfos_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
