# Generated by Django 5.0.6 on 2024-09-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0010_alter_userinfos_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/profile_pics/default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
