# Generated by Django 5.0.6 on 2024-09-08 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0012_alter_userinfos_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfos',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinfos',
            name='friends_requests',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
