# Generated by Django 5.0.6 on 2024-09-11 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0013_userinfos_friends_userinfos_friends_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_left', models.IntegerField(default=0)),
                ('score_right', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tournament_id', models.CharField(default='', max_length=200)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userinfos',
            name='match_history',
            field=models.ManyToManyField(blank=True, to='userManager.matchresults'),
        ),
    ]
