# Generated by Django 5.0.6 on 2024-09-17 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points1', models.IntegerField(default=0)),
                ('points2', models.IntegerField(default=0)),
                ('game_ws_id', models.CharField(default=0)),
                ('pool', models.IntegerField(default=1)),
                ('is_played', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('timer', models.IntegerField(default=180)),
                ('score', models.IntegerField(default=5)),
                ('top_spin', models.BooleanField(default=False)),
                ('back_spin', models.BooleanField(default=False)),
                ('side_spin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('psw', models.CharField(max_length=100)),
                ('matchesWon', models.IntegerField(default=0)),
                ('is_winner', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tournament', max_length=100)),
                ('winner', models.IntegerField(default=1)),
                ('round_number', models.IntegerField(default=1)),
                ('timer', models.IntegerField(default=180)),
                ('score', models.IntegerField(default=5)),
                ('top_spin', models.BooleanField(default=False)),
                ('back_spin', models.BooleanField(default=False)),
                ('side_spin', models.BooleanField(default=False)),
            ],
        ),
    ]
