# Generated by Django 5.0.6 on 2024-06-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
