# Generated by Django 5.0.6 on 2024-09-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_game_game_ws_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_winner',
        ),
        migrations.RemoveField(
            model_name='player',
            name='matchesWon',
        ),
        migrations.AddField(
            model_name='player',
            name='matches_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_ws_id',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to='database.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to='database.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournaments', to='database.player'),
        ),
    ]
