
# Generated by Django 5.0.6 on 2024-06-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_delete_tournament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='matchesWon',
            new_name='matchesWon',
        ),
    ]
