# Generated by Django 5.0.6 on 2024-09-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_game_game_ws_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pool',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
    ]
