# Generated by Django 5.0.6 on 2024-06-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rename_matches_won_player_matcheswon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tournament', max_length=100)),
                ('games', models.ManyToManyField(blank=True, to='database.game')),
                ('players', models.ManyToManyField(blank=True, to='database.player')),
            ],
        ),
    ]
