# Generated by Django 5.0.6 on 2024-09-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_player_is_winner_remove_player_matcheswon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tournament',
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('games', models.ManyToManyField(to='database.game')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='pools',
            field=models.ManyToManyField(blank=True, to='database.pool'),
        ),
    ]
