# Generated by Django 5.0.6 on 2024-06-25 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='is_played',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='database.tournament'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_winner',
            field=models.BooleanField(default=True),
        ),
    ]
