# Generated by Django 5.0.6 on 2024-09-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='faster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='game',
            name='slower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='timer',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='tournament',
            name='faster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tournament',
            name='slower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='timer',
            field=models.IntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner',
            field=models.IntegerField(blank=True),
        ),
    ]
