# Generated by Django 5.0.6 on 2024-06-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_tournament_games_game_is_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.IntegerField(default=1),
        ),
    ]
