# Generated by Django 5.0.6 on 2024-06-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_tournament_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='points',
        ),
        migrations.AddField(
            model_name='game',
            name='points1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='points2',
            field=models.IntegerField(default=0),
        ),
    ]
