# Generated by Django 5.0.6 on 2024-09-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_game_faster_game_score_game_slower_game_timer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='faster',
        ),
        migrations.RemoveField(
            model_name='game',
            name='slower',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='faster',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='slower',
        ),
        migrations.AddField(
            model_name='game',
            name='back_spin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='top_spin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='back_spin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='top_spin',
            field=models.BooleanField(default=False),
        ),
    ]
