# Generated by Django 5.0.6 on 2024-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_game_faster_remove_game_slower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='side_spin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='side_spin',
            field=models.BooleanField(default=False),
        ),
    ]
