# Generated by Django 5.0.6 on 2024-07-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_player_points_game_points1_game_points2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2',
        ),
    ]
