# Generated by Django 5.0.6 on 2024-09-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_game_side_spin_tournament_side_spin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='winner',
            field=models.IntegerField(default=1),
        ),
    ]
