# Generated by Django 5.0.6 on 2024-09-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_tournament_side_spin'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='side_spin',
            field=models.BooleanField(default=False),
        ),
    ]
