name:     transcendence

services:
  #********************************************************************************
  nginx:
    container_name: nginx
    image: nginx:1.27.0
    restart:        always
    healthcheck:
      test:         ["CMD", "curl", "-f", "http://localhost"]
      interval:     1m30s
      timeout:      10s
      retries:      3
    command: ["/nginx.sh", "nginx", "-g", "daemon off;"]
    depends_on:
      gunicorn:
        condition: service_started
      daphne:
        condition: service_started
    ports:
      - 8443:443
    volumes:
      - ../project/static_production:/static
      - ${PWD}/containers/scripts/nginx.sh:/nginx.sh
      - ${PWD}/containers/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
        - backend
        - frontend
  #********************************************************************************
  redis:
    container_name: redis
    image:          redis:7.2.5
    restart:        always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
        - backend
    # command: ["redis-server", "--loglevel", "debug"]
  #********************************************************************************
  db:
    container_name: postgres
    image:          postgres:16.3-bookworm
    restart:        always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U${DB_USER} -d${DB_NAME}"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
        - postgres01_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
        - backend
  #********************************************************************************
  daphne:
    container_name: daphne
    build:
      dockerfile:     ../containers/daphne/Dockerfile
      context:        ../containers 
    restart:        always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition:  service_started
    volumes:
      - ../project:/project
    networks:
        - backend
        - frontend
    environment:
      DB_NAME:      ${DB_NAME}
      DB_USER:      ${DB_USER}
      DB_PASSWORD:  ${DB_PASSWORD}
      DB_HOST:      db
      DB_PORT:      ${DB_PORT}
      SUPER_USER:   ${SUPER_USER}
      SUPER_PASSWORD:   ${SUPER_PASSWORD}
      SUPER_MAIL:   ${SUPER_MAIL}
  #********************************************************************************
  gunicorn:
    container_name: gunicorn
    build:          ../containers/gunicorn
    restart:        always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../project:/project
    networks:
        - backend
        - frontend
    environment:
      DB_NAME:      ${DB_NAME}
      DB_USER:      ${DB_USER}
      DB_PASSWORD:  ${DB_PASSWORD}
      DB_HOST:      db
      DB_PORT:      ${DB_PORT}
  #********************************************************************************

volumes:
  postgres01_data:


networks:
  backend:
  frontend:
