# Generated by Django 5.0.6 on 2024-07-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_alter_gamedb_players_username_alter_gamedb_winners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedb',
            name='players_username',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='gamedb',
            name='winners',
            field=models.JSONField(default=list),
        ),
    ]
